const EXERCISE_REFERENCE_BASE = 'https://raw.githubusercontent.com/yuhonas/free-exercise-db/main/exercises'

export const EXERCISE_IMAGES: Record<string, string> = {
  'bench press': `${EXERCISE_REFERENCE_BASE}/Barbell_Bench_Press_-_Medium_Grip/0.jpg`,
  'incline dumbbell press': `${EXERCISE_REFERENCE_BASE}/Incline_Dumbbell_Press/0.jpg`,
  'decline bench press': `${EXERCISE_REFERENCE_BASE}/Decline_Barbell_Bench_Press/0.jpg`,
  'cable flyes': `${EXERCISE_REFERENCE_BASE}/Cable_Crossover/0.jpg`,
  'dumbbell flyes': `${EXERCISE_REFERENCE_BASE}/Dumbbell_Flyes/0.jpg`,
  'push-ups': `${EXERCISE_REFERENCE_BASE}/Pushups/0.jpg`,
  'chest dips': `${EXERCISE_REFERENCE_BASE}/Dips_-_Chest_Version/0.jpg`,
  'pec deck machine': `${EXERCISE_REFERENCE_BASE}/Machine_Bench_Press/0.jpg`,
  'deadlift': `${EXERCISE_REFERENCE_BASE}/Barbell_Deadlift/0.jpg`,
  'lat pulldown': `${EXERCISE_REFERENCE_BASE}/Wide-Grip_Lat_Pulldown/0.jpg`,
  'barbell row': `${EXERCISE_REFERENCE_BASE}/Bent_Over_Barbell_Row/0.jpg`,
  'seated cable row': `${EXERCISE_REFERENCE_BASE}/Seated_Cable_Rows/0.jpg`,
  'pull-ups': `${EXERCISE_REFERENCE_BASE}/Pullups/0.jpg`,
  't-bar row': `${EXERCISE_REFERENCE_BASE}/T-Bar_Row_with_Handle/0.jpg`,
  'single arm dumbbell row': `${EXERCISE_REFERENCE_BASE}/One-Arm_Dumbbell_Row/0.jpg`,
  'face pulls': `${EXERCISE_REFERENCE_BASE}/Face_Pull/0.jpg`,
  'overhead press': `${EXERCISE_REFERENCE_BASE}/Standing_Military_Press/0.jpg`,
  'lateral raises': `${EXERCISE_REFERENCE_BASE}/Side_Lateral_Raise/0.jpg`,
  'front raises': `${EXERCISE_REFERENCE_BASE}/Front_Dumbbell_Raise/0.jpg`,
  'arnold press': `${EXERCISE_REFERENCE_BASE}/Arnold_Dumbbell_Press/0.jpg`,
  'rear delt flyes': `${EXERCISE_REFERENCE_BASE}/Reverse_Flyes/0.jpg`,
  'shrugs': `${EXERCISE_REFERENCE_BASE}/Barbell_Shrug/0.jpg`,
  'upright rows': `${EXERCISE_REFERENCE_BASE}/Upright_Barbell_Row/0.jpg`,
  'cable lateral raises': `${EXERCISE_REFERENCE_BASE}/Cable_Seated_Lateral_Raise/0.jpg`,
  'barbell curl': `${EXERCISE_REFERENCE_BASE}/Barbell_Curl/0.jpg`,
  'hammer curls': `${EXERCISE_REFERENCE_BASE}/Hammer_Curls/0.jpg`,
  'tricep pushdowns': `${EXERCISE_REFERENCE_BASE}/Triceps_Pushdown_-_Rope_Attachment/0.jpg`,
  'skull crushers': `${EXERCISE_REFERENCE_BASE}/EZ-Bar_Skullcrusher/0.jpg`,
  'preacher curls': `${EXERCISE_REFERENCE_BASE}/Preacher_Curl/0.jpg`,
  'overhead tricep extension': `${EXERCISE_REFERENCE_BASE}/Cable_Rope_Overhead_Triceps_Extension/0.jpg`,
  'concentration curls': `${EXERCISE_REFERENCE_BASE}/Concentration_Curls/0.jpg`,
  'dips': `${EXERCISE_REFERENCE_BASE}/Parallel_Bar_Dip/0.jpg`,
  'squat': `${EXERCISE_REFERENCE_BASE}/Barbell_Full_Squat/0.jpg`,
  'romanian deadlift': `${EXERCISE_REFERENCE_BASE}/Romanian_Deadlift/0.jpg`,
  'leg press': `${EXERCISE_REFERENCE_BASE}/Leg_Press/0.jpg`,
  'leg curl': `${EXERCISE_REFERENCE_BASE}/Seated_Leg_Curl/0.jpg`,
  'leg extension': `${EXERCISE_REFERENCE_BASE}/Leg_Extensions/0.jpg`,
  'lunges': `${EXERCISE_REFERENCE_BASE}/Dumbbell_Lunges/0.jpg`,
  'calf raises': `${EXERCISE_REFERENCE_BASE}/Standing_Calf_Raises/0.jpg`,
  'hip thrust': `${EXERCISE_REFERENCE_BASE}/Barbell_Hip_Thrust/0.jpg`,
  'crunches': `${EXERCISE_REFERENCE_BASE}/Crunches/0.jpg`,
  'plank': `${EXERCISE_REFERENCE_BASE}/Plank/0.jpg`,
  'hanging leg raise': `${EXERCISE_REFERENCE_BASE}/Hanging_Leg_Raise/0.jpg`,
  'russian twists': `${EXERCISE_REFERENCE_BASE}/Russian_Twist/0.jpg`,
  'ab wheel rollout': `${EXERCISE_REFERENCE_BASE}/Ab_Roller/0.jpg`,
  'cable crunches': `${EXERCISE_REFERENCE_BASE}/Cable_Crunch/0.jpg`,
  'mountain climbers': `${EXERCISE_REFERENCE_BASE}/Mountain_Climbers/0.jpg`,
  'dead bug': `${EXERCISE_REFERENCE_BASE}/Dead_Bug/0.jpg`,
  'treadmill run': `${EXERCISE_REFERENCE_BASE}/Running_Treadmill/0.jpg`,
  cycling: `${EXERCISE_REFERENCE_BASE}/Air_Bike/0.jpg`,
  'rowing machine': `${EXERCISE_REFERENCE_BASE}/Rowing_Stationary/0.jpg`,
  'jump rope': `${EXERCISE_REFERENCE_BASE}/Rope_Jumping/0.jpg`,
  'stair climber': `${EXERCISE_REFERENCE_BASE}/Stairmaster/0.jpg`,
  elliptical: `${EXERCISE_REFERENCE_BASE}/Elliptical_Trainer/0.jpg`,
  'hiit circuit': `${EXERCISE_REFERENCE_BASE}/Mountain_Climbers/0.jpg`,
  'battle ropes': `${EXERCISE_REFERENCE_BASE}/Battling_Ropes/0.jpg`,
  'incline bench press': `${EXERCISE_REFERENCE_BASE}/Barbell_Incline_Bench_Press_-_Medium_Grip/0.jpg`,
  'dumbbell fly': `${EXERCISE_REFERENCE_BASE}/Dumbbell_Flyes/0.jpg`,
  'cable fly': `${EXERCISE_REFERENCE_BASE}/Cable_Crossover/0.jpg`,
  'chest press machine': `${EXERCISE_REFERENCE_BASE}/Machine_Bench_Press/0.jpg`,
  'dumbbell row': `${EXERCISE_REFERENCE_BASE}/One-Arm_Dumbbell_Row/0.jpg`,
  'good morning': `${EXERCISE_REFERENCE_BASE}/Good_Morning/0.jpg`,
  'lateral raise': `${EXERCISE_REFERENCE_BASE}/Side_Lateral_Raise/0.jpg`,
  'front raise': `${EXERCISE_REFERENCE_BASE}/Front_Dumbbell_Raise/0.jpg`,
  'barbell shrug': `${EXERCISE_REFERENCE_BASE}/Barbell_Shrug/0.jpg`,
  'face pull': `${EXERCISE_REFERENCE_BASE}/Face_Pull/0.jpg`,
  'hammer curl': `${EXERCISE_REFERENCE_BASE}/Hammer_Curls/0.jpg`,
  'preacher curl': `${EXERCISE_REFERENCE_BASE}/Preacher_Curl/0.jpg`,
  'tricep pushdown': `${EXERCISE_REFERENCE_BASE}/Triceps_Pushdown_-_Rope_Attachment/0.jpg`,
  'close-grip bench': `${EXERCISE_REFERENCE_BASE}/Close-Grip_Barbell_Bench_Press/0.jpg`,
  'skull crusher': `${EXERCISE_REFERENCE_BASE}/EZ-Bar_Skullcrusher/0.jpg`,
  'concentration curl': `${EXERCISE_REFERENCE_BASE}/Concentration_Curls/0.jpg`,
  'back squat': `${EXERCISE_REFERENCE_BASE}/Barbell_Squat/0.jpg`,
  'calf raise': `${EXERCISE_REFERENCE_BASE}/Standing_Calf_Raises/0.jpg`,
  'front squat': `${EXERCISE_REFERENCE_BASE}/Front_Barbell_Squat/0.jpg`,
  'sit-ups': `${EXERCISE_REFERENCE_BASE}/Sit-Up/0.jpg`,
  'ab wheel': `${EXERCISE_REFERENCE_BASE}/Ab_Roller/0.jpg`,
  'russian twist': `${EXERCISE_REFERENCE_BASE}/Russian_Twist/0.jpg`,
  'cable crunch': `${EXERCISE_REFERENCE_BASE}/Cable_Crunch/0.jpg`,
  running: `${EXERCISE_REFERENCE_BASE}/Running_Treadmill/0.jpg`,
  burpees: `${EXERCISE_REFERENCE_BASE}/Mountain_Climbers/0.jpg`,
  'stationary bike': `${EXERCISE_REFERENCE_BASE}/Recumbent_Bike/0.jpg`,
  'power clean': `${EXERCISE_REFERENCE_BASE}/Power_Clean/0.jpg`,
  snatch: `${EXERCISE_REFERENCE_BASE}/Snatch/0.jpg`,
  'clean & jerk': `${EXERCISE_REFERENCE_BASE}/Clean_and_Jerk/0.jpg`,
  'muscle-up': `${EXERCISE_REFERENCE_BASE}/Muscle_Up/0.jpg`,
  'handstand push-up': `${EXERCISE_REFERENCE_BASE}/Handstand_Push-Ups/0.jpg`,
  'pistol squat': `${EXERCISE_REFERENCE_BASE}/Kettlebell_Pistol_Squat/0.jpg`,
  'dragon flag': `${EXERCISE_REFERENCE_BASE}/Hanging_Leg_Raise/0.jpg`,
}

export function getExerciseImageUrl(name: string): string | null {
  return EXERCISE_IMAGES[name.toLowerCase().trim()] ?? null
}
